version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: desafio_nuven
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/desafio_nuven?schema=public"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
